-- SQL Lite

BEGIN TRANSACTION;
DROP TABLE IF EXISTS "Tree";
CREATE TABLE IF NOT EXISTS "Tree" (
	"Id"	INTEGER NOT NULL UNIQUE,
	"Name"	TEXT NOT NULL,
	"Parent_Id"	INTEGER,
	PRIMARY KEY("Id" AUTOINCREMENT)
);
DROP TABLE IF EXISTS "Data";
CREATE TABLE "Data" (
	"Id"	INTEGER NOT NULL UNIQUE,
	"Tree_Id"	INTEGER NOT NULL,
	"Data"	BLOB,
	"Type"	INTEGER,
	PRIMARY KEY("Id" AUTOINCREMENT)
)
COMMIT;
